### ISSUE TITLE
[wiki] Users have expressed confusion about Step 1

### ISSUE THREAD

**Issue by chutten** [mozilla/data-review#10]
Users have come to me for clarification about how to file for Data Collection Review. The topics of confusion usually manifest as questions like

* "So am I supposed to just copy the form?"
* "Can I reuse the bug where I'm adding the probe?"
* "Does bugzilla support markdown now?"

I think this stems from a couple of wording choices and some perceived rigidity. For instance "clone" means something in git, so its use for the form suggests that users should fork the repo or create a gist or something, which is in conflict with the following substeps.

I propose a rewording:

To request a review, Data Review requesters require the following: 

* A completed Request Form, documenting what data is to be collected, why Mozilla needs to collect this data, how much data will be collected, and for how long it will be collected:
  * Take [this request](request.md) and fill it out completely (It is in markdown for easy reading of the template, but we understand bugzilla will likely render it as plain text. That's fine.)
* A bug to attach the completed Request Form to:
  * Attach the completed Request Form to the bug, or paste the contents as a comment in the Issue
  * Tip: reuse the bug you filed to add the collection code
* A notification so the Data Steward knows it's time to review your Request Form:
  * r? the attachment, ni? the bug, or @ the Data Steward on the GitHub Issue
  * If the Data Steward doesn't get back to you within a couple of days, please email [the list](mailto:fxdatastewardsorwhatever)

Bikeshed: begin

**Comment by fmarier** [comment]
Since you asked for my opinion on the colour of that fancy new bikeshed :)

> (It is in markdown for easy reading of the template, but we understand bugzilla will likely render it as plain text. That's fine.)

Maybe it should just be in plaintext to start with. It's kind of annoying having to look through the table markup when people use it. It would also avoid people having to rename the file manually to .txt so that it gets displayed inline in bugzilla.

**Comment by fmarier** [comment]
> Attach the completed Request Form to the bug, or paste the contents as a comment in the Issue

Personally, I'd like to discourage the "pasting into a comment" option. It makes the bug a lot noisier when there are a few iterations and it's harder to see which version of the data review request got approved. Also, it prevents us from using an r? flag.

**Comment by chutten** [comment]
> Personally, I'd like to discourage the "pasting into a comment" option. It makes the bug a lot noisier when there are a few iterations and it's harder to see which version of the data review request got approved. Also, it prevents us from using an r? flag.

I tried to specify that it's specifically for an Issue instead of a bug... but maybe we shouldn't be bending over backwards to supporting a GitHub-based flow for Data Review?

**Comment by fmarier** [comment]
Yeah, we should probably encourage a Bugzilla flow as much as possible. For example, the Activity Stream puts their [data review requests on Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1484035) even though they [use GitHub for development](https://github.com/mozilla/activity-stream/pull/4371). I find that easier to deal with because the Bugzilla notifications / reminders are much better.

**Comment by dbaron** [comment]
This rewording answers the questions I had about the [instructions](https://wiki.mozilla.org/Firefox/Data_Collection#Step_1:_Submit_Request).  (The other piece of confusion was the first item, saying " Create a bug using the data review bug form", which I thought both meant there was a [custom form](https://bugzilla.mozilla.org/page.cgi?id=custom_forms.html) and which I thought meant that I *shouldn't* reuse the bug.)

**Comment by chutten** [comment]
I've made some changes.

@fmarier Want to review the diff? https://wiki.mozilla.org/index.php?title=Firefox%2FData_Collection&type=revision&diff=1201350&oldid=1200054

**Comment by fmarier** [comment]
> I've made some changes.

It looks much better!

**Comment by chutten** [comment]
Alrighty, any further tweaks can come via follow-ups. Closing this bug.
