### ISSUE TITLE
[wiki] Category 3 language for opt-out eligibility on release is a little awkward

### ISSUE THREAD

**Issue by chutten** [mozilla/data-review#14]
A reader writes in noting some confusion on [the following paragraph](https://wiki.mozilla.org/Firefox/Data_Collection#Eligibility_for_Default_on_Data_Collection):

> Release: Default off. May be eligible for opt-out on a case-by-case basis if mitigations are identified. Mitigations may include UX changes that make users aware of additional risk, technical mechanisms that remove the risk, or a risk assessment done of a case-by-case basis that determines the risk is limited. 

The first and easiest to remedy is "risk assessment done of a case-by-case basis". This should probably be "on a case-by-case basis".

The second is that the reader wasn't clear on why, if it's default off, that we say it is eligible for opt-out. To use their words directly:

> If the default is off, shouldn't the option be to opt-in instead of opt-out, or do I misunderstand something?

I think we can restructure this slightly to make it clear that "Default off" is not only the default setting but is the default posture for collecting Category 3 data on release. We can maybe use formatting or word choice to highlight that mitigations to allow opt-out are an exception, not a clarifying statement.

**Comment by chutten** [comment]
@fmarier What do you think about this restructuring to make it clear that Default Off is the state, but there is an exception process?

* Release: Default Off
  * On a case-by-case basis collections may be eligible to be "default on" if mitigations are identified. Mitigations may include UX changes that make users aware of additional risk, technical mechanisms that remove the risk, or a risk assessment done of a case-by-case basis that determines the risk is limited.

**Comment by fmarier** [comment]
That sounds better to me.

**Comment by chutten** [comment]
Changes made:

https://wiki.mozilla.org/index.php?title=Firefox/Data_Collection&oldid=1202891
