### ISSUE TITLE
Create a question around private browsing behavior

### ISSUE THREAD

**Issue by rjweiss** [mozilla/data-review#6]
For Firefox measurement exclusively at this point, consider amending the existing data collection request forms with a question directed at providing a description of how the measurement should behave in private browsing mode.

**Comment by fmarier** [comment]
Are we actually collecting anything while in Private Browsing mode? I was under the impression we couldn't, as a matter of policy.

**Comment by chutten** [comment]
In many cases we simply do not distinguish in the data whether the data collection happened within PB or not.

**Comment by chutten** [comment]
I think we can go ahead and close this as seven months after my comment Ehsan posted to the governance list a [definitive policy on data collection about PBM](https://groups.google.com/d/msg/mozilla.governance/7UH_MngkDx0/M5CJnx4gCAAJ). In summary: we can collect if we want to, just like non-private-browsing mode. (though there might be a case to be made that Cat 3 and Cat 4 data should be from non-PBM contexts only, even with mitigations)
