### ISSUE TITLE
wiki page doesn't say which product + component to file the bug

### ISSUE THREAD

**Issue by groovecoder** [mozilla/data-review#9]
https://wiki.mozilla.org/Firefox/Data_Collection#Step_1:_Submit_Request doesn't say which product + component I should use to file the request.

**Comment by fmarier** [comment]
It would be whatever product/component the thing you're working on is in. There isn't a  separate product/component for data requests. They are part of the same product/component where the feature is being worked on.

**Comment by groovecoder** [comment]
I added that text to https://wiki.mozilla.org/Firefox/Data_Collection#Step_1:_Submit_Request

**Comment by fmarier** [comment]
Thanks @groovecoder !
